# Generated by Django 4.2.23 on 2026-06-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phong_tro', '0001_initial'),
        ('nguoi_thue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Còn hiệu lực'), ('ENDED', 'Đã kết thúc')], default='ACTIVE', max_length=20)),
                ('room', models.ForeignKey(db_column='room_code', on_delete=django.db.models.deletion.CASCADE, to='phong_tro.room')),
                ('tenant', models.ForeignKey(db_column='tenant_code', on_delete=django.db.models.deletion.CASCADE, to='nguoi_thue.tenant')),
            ],
            options={
                'db_table': 'hop_dong',
            },
        ),
    ]
