# Generated by Django 4.2.23 on 2026-06-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('area', models.FloatField(default=0)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('EMPTY', 'Trống'), ('RENTED', 'Đang thuê'), ('MAINTENANCE', 'Bảo trì')], default='EMPTY', max_length=20)),
            ],
            options={
                'db_table': 'phong_tro',
            },
        ),
    ]
