# Generated by Django 4.2.23 on 2026-06-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tai_khoan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('citizen_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('account', models.OneToOneField(blank=True, db_column='account_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tai_khoan.account')),
            ],
            options={
                'db_table': 'nguoi_thue',
            },
        ),
    ]
