# Generated by Django 4.2.23 on 2026-06-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hop_dong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('room_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán')], default='UNPAID', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('contract', models.ForeignKey(db_column='contract_code', on_delete=django.db.models.deletion.CASCADE, to='hop_dong.contract')),
            ],
            options={
                'db_table': 'hoa_don',
            },
        ),
    ]
