# Generated by Django 4.2.23 on 2026-06-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('LANDLORD', 'Chủ trọ'), ('TENANT', 'Người thuê')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('LOCKED', 'Khóa')], default='ACTIVE', max_length=20)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tai_khoan',
            },
        ),
    ]
