# Generated by Django 4.2.23 on 2026-06-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalService',
            fields=[
                ('service_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_name', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'dich_vu',
            },
        ),
    ]
