# Generated by Django 4.2.23 on 2026-06-04 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phong_tro', '0001_initial'),
        ('dich_vu_phong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReading',
            fields=[
                ('reading_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('old_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rental_service', models.ForeignKey(db_column='service_code', on_delete=django.db.models.deletion.CASCADE, to='dich_vu_phong.rentalservice')),
                ('room', models.ForeignKey(db_column='room_code', on_delete=django.db.models.deletion.CASCADE, to='phong_tro.room')),
            ],
            options={
                'db_table': 'chi_so_dich_vu',
            },
        ),
    ]
